server:
  port: 10000

logging:
  level:
    root: WARN
    es.upm.api: INFO

app:
  hosting: AWS

spingdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}